name:                Runge-Kutta
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- Chart
- Chart-diagrams

executables:
  Runge-Kutta-method:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
