name:                Runge-Kutta
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- Chart
- Chart-diagrams
- Chart-cairo

library:
  source-dirs: src

executables:
  Runge-Kutta:
    main:                Main.hs
    source-dirs:         Runge-Kutta
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Runge-Kutta
  Euler:
    main:                Main.hs
    source-dirs:         Euler
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
