name:                Runge-Kutta
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- Chart
- Chart-diagrams
- Chart-cairo

executables:
  Runge-Kutta:
    main:                Runge-Kutta.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
